### ISSUE TITLE
Foreign key `Source_ID` is empty in `facttable` for pluvio data

### ISSUE THREAD

**Issue by scheidan** [Eawag-DataWareHouse/SDWH#22]
This is only the case for the pluvio data.

**Comment by scheidan** [comment]
Found the reason for it but I don't understand: If the field `serial` is left empty in the `source_matedata.xml` then the `source_ID` field in the `factTable` remains empty. Why?

**Comment by daksa** [comment]
also related #13

**Comment by tobdop** [comment]
Its because serial is used for lookup. at the moment it works if `serial` and `source_ID` are unique in the `source_metadata.xml`
